### ISSUE TITLE
Remember managed mappings

### ISSUE THREAD

**Issue by henninge** [inovex/aws-auth-controller#3]
Currently the controller rewrites the aws-auth ConfigMap completely, using all mappings. The main reason for this is to catch deleted mappings or ARNs. The problem is that this has to do special casing for "system:node:" users which are created by EKS. This is based on reverse engineering and we do not know what other mappings we might accidentally delete. The controller needs to be a better citizen when modifying the ConfigMap. It needs to know which entries it manages and not touch any others.

For this we need extra custom resources to represent the internal state of the controller. These store the information about which role/user ARNs are being managed by the controller. In addition we should rename "AwsAuthMap"  so that it is clear that is just a part of the actual map. "Snippet", "Entry",  "Mapping" are good candiates.

## Proposed Custom Resources

- Rename AwsAuthMap to AwsAuthMapSnippet but leave the specification the same
- Add AwsAuthMapEntries which corresponds to a AwsAuthMapSnippet of the same name. It remembers which ARNs were mapped and holds a checksum of the Snippet content.

```
apiVersion: crd.awsauth.io/v1beta2
kind: AwsAuthMapSnippet
metadata:
  name: firstauth
  namespace: firstauth-namespace
spec:
  mapRoles:
    - rolearn: arn:aws:iam::111122223333:role/foo
      username: foo-user
      groups:
        - foo-group
    - rolearn: arn:aws:iam::111122223333:role/bar
      username: bar-user
      groups:
        - bar-group
  mapUsers:
    - userarn: arn:aws:iam::111122223333:user/foo
      username: foo-user
      groups:
        - foo-group
    - userarn: arn:aws:iam::111122223333:user/bar
      username: bar-user
      groups:
        - bar-group
---
apiVersion: crd.awsauth.io/v1beta2
kind: AwsAuthMapEntries
metadata:
  name: firstauth
  namespace: firstauth-namespace
spec:
  checkSum: 1234567789abcdefvg
  roleArns:
    - arn:aws:iam::111122223333:role/foo
    - arn:aws:iam::111122223333:role/bar
 userArns:
    - arn:aws:iam::111122223333:user/foo
    - arn:aws:iam::111122223333:user/bar
```
 
## Proposed Operations

Startup, add and update operations must also include duplicate checks for the ARNs against the ConfigMap.

### Controller Startup

1. Compare all Snippets and Entries by name only
2. Remove all entries from the ConfigMap that have no corresponding Snippet
3. Remove those Entries CRDs, too.
4. Create Entries for Snippets that have none.
5. Compare the checksum in the Entries with the Snippet 
6. Update Entries where checksum does not match
7. Update or add all Snippets in the ConfigMap.

### New Snippet

1. Create corresponding Entries resource and calculate checksum
2. Add the entries to the ConfigMap

### Update Snippet

1. Find corresponding Entries resource and compare checksum
2. If changed, compare list of ARNs
3. Remove any entries from the ConfigMap that are now missing in the Snippet
4. Add any entries to the ConfigMap that are new in the Snippet
5. Update all other entries from the Snippet  in the ConfigMap
6. Update Entries resource to match the Snippet resource (ARNs and checkSum)

### Snippet Deletion

Remember that Snippet is not available as the Reconcile loop is triggered after it has been deleted.

1. Find Entries resource with the deleted name
2. Delete all entries from the ConfigMap
3. Delete the Entries resource.
